name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
    id-token: "write"
    contents: "write"
    packages: "write"
    pull-requests: "read"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Flask
        path: ./*/build/libs/flask-*.jar
    - run: 'ls -R'
    # - uses: thecodemonkey/action-get-gradle-version@master
    #   id: version
    #   with:
    #     file: 
    - run: 'echo version ${{ steps.version.outputs.version }}'
    
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Get Version
      run: 'echo version ${{ needs.build.outputs.version }}'
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: Flask
