name: Create Release

on:
  workflow_run:
    workflows: ["Build"]
    types: ["completed"]
    branches:
      - 'main'

jobs:
  download:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Flask
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ env.REPO_TOKEN }}
      - name: Display Files
        run: ls -R
