name: Create Release

on:
  workflow_run:
    workflows: ["Build"]
    types: ["completed"]
    branches:
      - 'main'

jobs:
  upload:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4.1.9
        with:
          name: flask
      - name: Display Files
        run: ls -R
